/**
 * AISourceChip — small inline tag declaring the source-of-truth for an
 * AI-generated panel ("based on your profile inputs above"). Renders as a
 * muted, low-emphasis chip so users can see what the model was given to
 * work from. Server-component-friendly (no hooks, no client APIs).
 *
 * Uses existing CSS variables (--text-muted, --border) only -- no new tokens.
 *
 * The `model` prop surfaces which AI produced this output for transparency.
 * When omitted, no model name is shown -- just the source description.
 */
export function AISourceChip({
  children,
  model,
}: {
  children: React.ReactNode;
  /** Optional: which AI model produced this (e.g. "Llama 3.1 8B"). */
  model?: string;
}) {
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 align-middle"
      style={{
        fontSize: "11px",
        lineHeight: 1.4,
        color: "var(--dl-text-muted, #5A6275)",
        borderColor: "rgba(0,0,0,0.06)",
        backgroundColor: "transparent",
      }}
      title={model ? `Generated by ${model}` : "AI-generated content"}
    >
      <span
        aria-hidden="true"
        style={{
          width: "5px",
          height: "5px",
          borderRadius: "9999px",
          backgroundColor: "#4A6FA5",
          opacity: 0.7,
        }}
      />
      {children}
      {model && (
        <span
          style={{
            fontSize: "10px",
            opacity: 0.7,
            borderLeft: "1px solid rgba(0,0,0,0.08)",
            paddingLeft: "6px",
            marginLeft: "2px",
          }}
        >
          {model}
        </span>
      )}
    </span>
  );
}

export default AISourceChip;
